#!/usr/bin/env bash

THIS="$(realpath "$0")"
HEREDIR="$(dirname "$THIS")"
SCRIPT="$(basename "$0")"

set -euo pipefail

main() {
    if [[ "$*" =~ ^update ]]; then
        shift
        cd "$HEREDIR"
        set -e
        git pull
        sudo bash "$HEREDIR/services/install.sh" "$@"
        sudo systemctl restart foghorn
    else
        exec python3 "$HEREDIR/src/foghorn.py" "$@"
    fi
}

main "$@"
