networks:
  fog:
    ipam:
      driver: default
      config:
      - subnet: 192.168.42.248/29

services:

  fog1:
    image: foghorn:latest
    volumes:
    - ../:/hostdata
    - ./:/demodata
    hostname: demo-fog1
    command: bash ./demo.sh spin-up fog1 192.168.42.248/29
    networks:
    - fog

  fog2:
    image: foghorn:latest
    volumes:
    - ../:/hostdata
    - ./:/demodata
    hostname: demo-fog2
    command: bash ./demo.sh spin-up fog2 192.168.42.248/29
    networks:
    - fog

  fog3:
    image: foghorn:latest
    volumes:
    - ../:/hostdata
    - ./:/demodata
    hostname: demo-fog3
    command: bash ./demo.sh spin-up fog3 192.168.42.248/29
    networks:
    - fog